apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: app-instrumentation
  namespace: boutique
spec:
  env:
    - name: FRONTEND_PUBLIC_OTEL_ENDPOINT
      value: "http://136.112.127.68:4318/v1/traces"
  exporter:
    endpoint: http://trace-collector-collector.monitoring.svc:4317
  
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: '1'

  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://trace-collector-collector.monitoring.svc:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
    
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.46b0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://trace-collector-collector.monitoring.svc:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"

  java:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"

  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"

  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://trace-collector-collector.monitoring.svc:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED
        value: "true"
      - name: OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED
        value: "true"

#working code 
# apiVersion: opentelemetry.io/v1alpha1
# kind: Instrumentation
# metadata:
#   name: app-instrumentation
#   namespace: boutique
# spec:
#   exporter:
#     endpoint: http://trace-collector-collector.monitoring.svc:4317
  
#   propagators:
#     - tracecontext
#     - baggage
#   sampler:
#     type: parentbased_traceidratio
#     argument: '1'


#   go:
#     env:
#     - name: OTEL_EXPORTER_OTLP_ENDPOINT
#       value: "http://trace-collector-collector.monitoring.svc:4317"
#     - name: OTEL_EXPORTER_OTLP_PROTOCOL
#       value: "grpc"

#   python:
#     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.46b0
#     env:
#     - name: OTEL_EXPORTER_OTLP_ENDPOINT
#       value: "http://trace-collector-collector.monitoring.svc:4317"
#     - name: OTEL_EXPORTER_OTLP_PROTOCOL
#       value: "grpc"

#   java:
#     env:
#       - name: OTEL_EXPORTER_OTLP_PROTOCOL
#         value: "grpc"

#   nodejs:
#     env:
#       - name: OTEL_EXPORTER_OTLP_PROTOCOL
#         value: "grpc"

#   dotnet:
#     env:
#       # Use gRPC for .NET traces
#       - name: OTEL_EXPORTER_OTLP_ENDPOINT
#         value: "http://trace-collector-collector.monitoring.svc:4317"
#       - name: OTEL_EXPORTER_OTLP_PROTOCOL
#         value: "grpc"
#       # Enable the auto-instrumentation features
#       - name: OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED
#         value: "true"
#       - name: OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED
#         value: "true"
