deploymentName: emailservice-deployment
serviceName: emailservice
appLabel: emailservice
appName: emailservice
serviceAccountName: emailservice

replicaCount: 1

image:
  repository: registry.gitlab.com/seunayolu/gitops-currencyservice/currencyservice
  tag: "89d6f18c"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: my-registry-key

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

containers:
  - name: server
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      periodSeconds: 5
      grpc:
        port: 8080
    livenessProbe:
      periodSeconds: 5
      grpc:
        port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

service:
  type: ClusterIP
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080

createServiceAccount: true
profiler_enabled:  false