# global:
#   configMapName: online-boutique-dev-configmap
#   activeProfile: default

#   redis:
#     address: "redis-cart.default.svc.cluster.local:6379"

#   # ingress:
#   #   certificateArn: arn:aws:acm:eu-north-1:381492137122:certificate/4a115c36-439e-4981-8be2-6020324e3400
#   #   scheme: internet-facing
#   #   targetType: ip
#   #   className: alb
#   #   groupName: online-boutique
#   #   listenPorts: '[{"HTTP": 80}, {"HTTPS": 443}]'

#   services:
#     productcatalogservice: true
#     currencyservice: true
#     cartservice: true
#     recommendationservice: true
#     shippingservice: true
#     checkoutservice: true
#     adservice: true
#     shoppingassistantservice: true



# # frontend ingress overrides
# # online-boutique-common:
# #   ingress:
# #     enabled: true
# #     host: frontend-dev.dominicsheytanya.org
# #     serviceName: frontend
# #     servicePort: 80

#   features:
#     enableTracing: "true"
#     enable_profiler: "fale"

--- 
global:
  configMapName: online-boutique-dev-configmap
  activeProfile: default

  redis:
    address: "redis-cart.default.svc.cluster.local:6379"

  #SERVICE DISCOVERY ADDRESSES
  services:
    productcatalogservice: "productcatalogservice:3550"
    currencyservice: "currencyservice:7000"
    cartservice: "cartservice:7070"
    recommendationservice: "recommendationservice:8080"
    shippingservice: "shippingservice:50051"
    checkoutservice: "checkoutservice:5050"
    adservice: "adservice:9555"


  features:
    enableTracing: "true"
    enable_profiler: "false"