deploymentName: cartservice-deployment
serviceName: cartservice

appLabel: cartservice
appName: cartservice
jobLabel: cartservice

replicaCount: 1

image:
  repository: ghcr.io/tanya-domi/cartservice
  tag: "18823055103"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: my-registry-key

terminationGracePeriodSeconds: 5

annotations:
  instrumentation.opentelemetry.io/inject-dotnet: "app-instrumentation"

containers:
  - name: server
    ports:
      - containerPort: 7070
    env:
      - name: REDIS_ADDR
        value: "redis-cart:6379"
    readinessProbe:
      initialDelaySeconds: 15
      grpc:
        port: 7070
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      grpc:
        port: 7070
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 7070
  targetPort: 7070

serviceAccount:
  create: true
  name: "cartservice"

profiler_enabled: "false"

