deploymentName: paymentservice-deployment
serviceName: paymentservice

appLabel: paymentservice
appName: paymentservice
jobLabel: paymentservice

replicaCount: 1

image:
  repository: ghcr.io/tanya-domi/paymentservice
  tag: "docker-18816493323"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: my-registry-key

annotations:
  instrumentation.opentelemetry.io/inject-nodejs: "app-instrumentation"

containers:
  - name: server
    ports:
      - containerPort: 50051
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
    readinessProbe:
      grpc:
        port: 50051
    livenessProbe:
      grpc:
        port: 50051
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 50051
  targetPort: 50051

serviceAccount:
  create: true
  name: "paymentservice"

profiler_enabled: "false"
