deploymentName: adservice-deployment
serviceName: adservice

appLabel: adservice
appName: adservice
jobLabel: adservice

replicaCount: 1

image:
  repository: ghcr.io/tanya-domi/adservice
  tag: "docker-18816493323"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: my-registry-key
terminationGracePeriodSeconds: 5

annotations:
  instrumentation.opentelemetry.io/inject-java: "app-instrumentation"

containers:
  - name: server
    ports:
      - containerPort: 9555
    env:
      - name: PORT
        value: "9555"
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      grpc:
        port: 9555
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      grpc:
        port: 9555
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 9555
  targetPort: 9555

serviceAccount:
  create: true
  name: "adservice"


profiler_enabled: "false"
