{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName}}
  namespace: {{ .Release.Namespace }}
data:
  PRODUCT_CATALOG_SERVICE_ADDR: "{{ .Values.global.services.productcatalogservice  }}"
  CURRENCY_SERVICE_ADDR: "{{ .Values.global.services.currencyservice  }}"
  CART_SERVICE_ADDR: "{{ .Values.global.services.cartservice  }}"
  RECOMMENDATION_SERVICE_ADDR: "{{ .Values.global.services.recommendationservice  }}"
  SHIPPING_SERVICE_ADDR: "{{ .Values.global.services.shippingservice  }}"
  CHECKOUT_SERVICE_ADDR: "{{ .Values.global.services.checkoutservice  }}"
  AD_SERVICE_ADDR: "{{ .Values.global.services.adservice  }}"
  REDIS_ADDR: "{{ .Values.global.redis.address  }}"
  ENABLE_PROFILER: "{{ .Values.global.profiler_enabled }}"
{{- end -}}


