{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    
    spec:
       {{- if .Values.shareProcessNamespace }}
      shareProcessNamespace: true
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}

      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: false
        runAsUser: 1000

      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          {{- with .ports }}
          ports:
            {{- range . }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          {{- end }}

          {{- if or .env $.Values.global.configMapName }}
          env:
            {{- if .env }}
            {{- range .env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}

            {{- if $.Values.global.configMapName }}
            - name: ENABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: ENABLE_PROFILER
            {{- end }}

            {{- if $.Values.env }}
              {{- if $.Values.env.productcatalogservice }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: PRODUCT_CATALOG_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.currencyservice }}
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: CURRENCY_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.cartservice }}
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: CART_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.recommendationservice }}
            - name: RECOMMENDATION_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: RECOMMENDATION_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.shippingservice }}
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: SHIPPING_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.checkoutservice }}
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: CHECKOUT_SERVICE_ADDR
              {{- end }}

              {{- if $.Values.env.adservice }}
            - name: AD_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.global.configMapName }}
                  key: AD_SERVICE_ADDR
              {{- end }}
            {{- end }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds | default 5 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
            failureThreshold: {{ .failureThreshold | default 3 }}
            {{- if .httpGet }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
              {{- with .httpGet.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- else if .grpc }}
            grpc:
              port: {{ .grpc.port }}
              {{- if .grpc.service }}
              service: {{ .grpc.service }}
              {{- end }}
            {{- else if .tcpSocket }}
            tcpSocket:
              port: {{ .tcpSocket.port }}
            {{- end }}
          {{- end }}

          {{- with .readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .initialDelaySeconds | default 5 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
            failureThreshold: {{ .failureThreshold | default 3 }}
            {{- if .httpGet }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
              {{- with .httpGet.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            {{- else if .grpc }}
            grpc:
              port: {{ .grpc.port }}
              {{- if .grpc.service }}
              service: {{ .grpc.service }}
              {{- end }}
            {{- end }}
          {{- end }}

          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
{{- end }}
