{{- define "common.ingress" -}}
{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default (printf "%s-ingress" .Release.Name) }}
  labels:
    {{- include "microservices-chart.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    {{- end }}
    {{- if .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    {{- end }}
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    {{- end }}
    {{- if .Values.ingress.listenPorts }}
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.ingress.listenPorts }}'
    {{- end }}
    {{- if .Values.ingress.sslRedirect }}
    alb.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    {{- end }}
    {{- if .Values.ingress.groupName }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend
            port:
              number: 80
  {{- end }}
{{- end }}
{{- end }}


