apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch-sysctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: elasticsearch-sysctl
  template:
    metadata:
      labels:
        name: elasticsearch-sysctl
    spec:
      hostPID: true
      containers:
      - name: sysctl
        image: busybox:latest
        command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144; sleep 3600
        securityContext:
          privileged: true
      tolerations:
      - operator: Exists
